import type { PackSeed } from './pack-util'
import { c } from './pack-util'

/** JavaScript, Python, OOP — Week 1 topics. */
export const PACKS_CORE: PackSeed[] = [
  {
    key: 'js-closures',
    title: 'Closures',
    topic: 'JavaScript closures',
    track: 'CORE_CS',
    weekNumber: 1,
    tags: ['javascript', 'closures', 'scope'],
    summary: 'A function plus the variables it was born next to — and why loops print 3, 3, 3.',
    cards: [
      c('HOOK', 'Why does this print 3, 3, 3?', 'Three timers are set inside a loop. Each is meant to print its own `i`. All three print `3`.\n\nThe bug isn’t in `setTimeout`. It’s in what a function *remembers*.', 'for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}\n// 3, 3, 3', 'js'),
      c('CONCEPT', 'A function and the scope it was born in', 'A **closure** is a function bundled with a reference to the lexical environment where it was created. The function can still read and write those variables after the outer function has returned.\n\nTwo things to hold on to:\n\n- It captures **variables**, not values. It’s a live link to the binding, not a snapshot.\n- “Lexical” means the scope is fixed by where the code is *written*, not where it is *called*.'),
      c('EXAMPLE', 'A private counter', 'Call `makeCounter()` twice and you get two independent counters. Each call creates a fresh environment holding its own `count`, and the returned function keeps that environment alive.\n\nNothing outside can touch `count` except through the function you handed out. That is how JavaScript did private state long before `#private` fields.'),
      c('CODE', 'makeCounter', 'Two calls, two environments:', 'function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\n\nconst a = makeCounter();\nconst b = makeCounter();\na(); a();   // 1, 2\nb();        // 1  (a separate environment)', 'js'),
      c('ANALOGY', 'A backpack', 'When a function leaves the place where it was defined, it takes a backpack with it. Inside the backpack are the variables it could see back home.\n\nWherever it ends up being called, it opens the backpack — not the room it’s standing in — to look up `count`.'),
      c('WARNING', 'The loop trap, and the leak', '**The loop trap.** `var` is function-scoped: the loop has *one* `i`, shared by all three callbacks, and it is `3` by the time they run. `let` creates a fresh binding per iteration, so each callback closes over its own `i`.\n\n**The leak.** A closure keeps everything it captured alive. A small callback that accidentally closes over a huge array keeps that array in memory for as long as the callback lives.'),
      c('CHECK', 'Predict it', 'Q: What does this print, and why?\n\n`for (let i = 0; i < 3; i++) setTimeout(() => console.log(i), 0)`\n\nA: `0, 1, 2`. With `let`, every iteration gets its own `i`, and each callback closes over its own copy of the binding.'),
      c('SUMMARY', 'Closures in four lines', '- A closure = a function + the scope it was created in.\n- It captures variables (live), not values.\n- Each call to the outer function makes a new, private environment.\n- `var` in loops shares one binding; `let` gives one per iteration.'),
    ],
  },
  {
    key: 'js-event-loop',
    title: 'The Event Loop',
    topic: 'JavaScript event loop',
    track: 'CORE_CS',
    weekNumber: 1,
    tags: ['javascript', 'event loop', 'async'],
    summary: 'One thread, two queues: why `setTimeout(fn, 0)` runs after a resolved promise.',
    cards: [
      c('HOOK', '`setTimeout(fn, 0)` isn’t zero', 'JavaScript runs one thing at a time, yet it handles timers, network and clicks without freezing. The trick is a loop that decides what runs next.\n\nTry predicting the output of the snippet on the next cards before you read the explanation.'),
      c('CONCEPT', 'Stack, queues, loop', 'JavaScript has a single **call stack**. Timers, network and UI events are handled by the host (browser or Node); when they finish, their callbacks wait in a queue.\n\nThe **event loop** runs forever: *when the stack is empty, take the next task.*\n\nThere are two queues:\n\n- **Macrotasks** (task queue): timers, I/O, UI events.\n- **Microtasks**: promise reactions, `queueMicrotask`.\n\nAfter the stack empties, the loop drains the **entire** microtask queue before taking the next macrotask.'),
      c('EXAMPLE', 'Walk through it', '1. `log("A")` runs now → **A**.\n2. `setTimeout` hands the callback to the timer system; it will queue a *macrotask* later.\n3. `Promise.resolve().then(…)` queues a *microtask* immediately.\n4. `log("D")` runs now → **D**.\n5. Stack empty → drain microtasks → **C**.\n6. Next macrotask → **B**.\n\nOrder: A, D, C, B.'),
      c('CODE', 'The puzzle', 'Sync first, then microtasks, then macrotasks:', 'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("D");\n// A D C B', 'js'),
      c('ANALOGY', 'One cashier, two trays', 'A single cashier serves one customer at a time (the stack). New customers wait in a line (macrotasks).\n\nBut the cashier also has a tray of sticky notes (microtasks). Before calling the next person from the line, she clears **every** sticky note — including any new ones written while she’s clearing.'),
      c('WARNING', 'Block it and you freeze everything', 'A long synchronous loop holds the stack: no clicks, no rendering, no timers. A `setTimeout` delay is a *minimum*, not a promise.\n\nMicrotasks can also starve the loop: a promise chain that keeps scheduling more microtasks stops the next macrotask (and rendering) from ever running.'),
      c('CHECK', 'Predict the order', 'Q: In what order does this print?\n\n`console.log(1); setTimeout(() => console.log(2)); Promise.resolve().then(() => console.log(3)); (async () => { console.log(4); await null; console.log(5); })(); console.log(6);`\n\nA: `1, 4, 6, 3, 5, 2`. The async function runs synchronously until its first `await` (prints 4); the continuation is a microtask queued after the `.then`, so 3 comes before 5; the timer is a macrotask, so 2 is last.'),
      c('SUMMARY', 'The loop in four lines', '- One thread, one call stack.\n- Sync code first; then *all* microtasks; then one macrotask; repeat.\n- Promises → microtasks. Timers and I/O → macrotasks.\n- Never block the stack; never starve it with endless microtasks.'),
    ],
  },
  {
    key: 'js-promises',
    title: 'Promises',
    topic: 'JavaScript promises',
    track: 'CORE_CS',
    weekNumber: 1,
    tags: ['javascript', 'promises', 'async'],
    summary: 'A value that doesn’t exist yet: states, chaining, and the mistakes everyone makes once.',
    cards: [
      c('HOOK', 'A value that doesn’t exist yet', '`fetch()` returns *before* the data does. So what are you holding in the meantime?\n\nA **promise**: an object standing in for a result that will arrive later — or fail trying.'),
      c('CONCEPT', 'Three states, settled once', 'A promise is **pending**, then becomes either **fulfilled** (with a value) or **rejected** (with a reason). Once settled it never changes.\n\n`.then(onFulfilled)` registers a callback; callbacks always run asynchronously, as microtasks. And `.then` returns a **new** promise:\n\n- return a value → the next promise fulfills with it;\n- throw → the next promise rejects;\n- return a promise → the next one adopts its outcome.'),
      c('EXAMPLE', 'A chain that reads top to bottom', 'Load a user, then their posts, then count them. Each step waits for the previous. A single `.catch` at the end handles a failure from *any* step above it, and `.finally` runs either way — a good place to hide a spinner.'),
      c('CODE', 'Chain vs async/await', 'The same logic two ways:', 'getUser(id)\n  .then((u) => getPosts(u.id))\n  .then((posts) => posts.length)\n  .catch(() => 0)\n  .finally(() => hideSpinner());\n\nasync function count(id) {\n  try {\n    const u = await getUser(id);\n    return (await getPosts(u.id)).length;\n  } catch {\n    return 0;\n  }\n}', 'js'),
      c('ANALOGY', 'The restaurant pager', 'You order and get a buzzer. You’re free to do other things. It eventually buzzes with your food (fulfilled) or with “sorry, we’re out” (rejected). You can’t un-buzz it, and it only ever buzzes once.'),
      c('WARNING', 'The usual mistakes', '- **Forgetting to `return`** inside `.then` — the next step receives `undefined`.\n- **`await` in a loop** runs requests one after another. For independent work, start them together with `Promise.all`.\n- `Promise.all` rejects as soon as one rejects; use `Promise.allSettled` when you need every outcome.\n- An unhandled rejection is a bug that surfaces late. Always end a chain with `.catch` or wrap `await` in `try`.'),
      c('CHECK', 'What does it log?', 'Q: `Promise.resolve(1).then((x) => { x + 1 }).then((x) => console.log(x))`\n\nA: `undefined`. The first callback uses braces without `return`, so it returns nothing and the next step receives `undefined`.'),
      c('SUMMARY', 'Promises in four lines', '- pending → fulfilled | rejected, exactly once.\n- `.then` returns a new promise: that’s what makes chains.\n- Return values; throw errors; end with `.catch`.\n- Independent work → `Promise.all`, not `await` in a loop.'),
    ],
  },
  {
    key: 'py-decorators-generators',
    title: 'Python decorators & generators',
    topic: 'Python decorators and generators',
    track: 'CORE_CS',
    weekNumber: 1,
    tags: ['python', 'decorators', 'generators'],
    summary: 'Wrap a function without editing it; stream a million items in constant memory.',
    cards: [
      c('HOOK', 'Two superpowers', 'How do you time *every* function without editing each one? How do you read a 40 GB file using 40 MB of memory?\n\nThe first is a **decorator**. The second is a **generator**. Both are just functions, used cleverly.'),
      c('CONCEPT', 'Functions that wrap, functions that pause', 'A **decorator** is a callable that takes a function and returns a replacement (usually a wrapper). `@d` above a `def` is sugar for `f = d(f)`.\n\nA **generator** is a function containing `yield`. Calling it returns an iterator without running anything; each `next()` runs the body until the next `yield`, then pauses with all its local state intact.'),
      c('EXAMPLE', 'Timing and streaming', 'The timing decorator wraps `work` so each call prints its duration, with no change to `work` itself.\n\nThe Fibonacci generator is an *infinite* sequence: it only ever computes the next value when asked, so `islice` can take the first eight without any list being built.'),
      c('CODE', 'Both in one place', '', 'import functools, time\nfrom itertools import islice\n\ndef timed(fn):\n    @functools.wraps(fn)\n    def wrapper(*args, **kwargs):\n        t0 = time.perf_counter()\n        try:\n            return fn(*args, **kwargs)\n        finally:\n            print(f"{fn.__name__}: {time.perf_counter() - t0:.4f}s")\n    return wrapper\n\n@timed\ndef work(n):\n    return sum(range(n))\n\ndef fib():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\nlist(islice(fib(), 8))   # [0, 1, 1, 2, 3, 5, 8, 13]', 'python'),
      c('ANALOGY', 'Gift-wrap and vending machine', 'A decorator is gift-wrapping: same present inside, new behaviour around it.\n\nA generator is a vending machine: it gives you one item per request. A normal function is a truck that delivers the whole warehouse at once.'),
      c('WARNING', 'Sharp edges', '- Forget `functools.wraps` and the wrapper hides the original `__name__` and docstring — which breaks debugging and some frameworks.\n- A generator is **single-use**. Once exhausted, iterating it again yields nothing.\n- A decorator that takes arguments needs one more layer of nesting: `@retry(3)` calls `retry(3)` first, and *that* returns the real decorator.'),
      c('CHECK', 'Exhausted', 'Q: `g = (x * x for x in range(3)); print(list(g)); print(list(g))` — what prints?\n\nA: `[0, 1, 4]` then `[]`. A generator expression is an iterator; the first `list()` consumes it, so the second sees nothing.'),
      c('SUMMARY', 'In four lines', '- `@d` means `f = d(f)`.\n- Use `functools.wraps` in every wrapper.\n- `yield` makes a lazy, pausable, single-use iterator.\n- Generators give constant memory; reach for them when data is large or infinite.'),
    ],
  },
  {
    key: 'oop-composition',
    title: 'Composition over inheritance',
    topic: 'Composition over inheritance',
    track: 'OOP_LLD',
    weekNumber: 1,
    tags: ['oop', 'design', 'composition', 'lld'],
    summary: 'Has-a beats is-a when behaviour needs to vary: build with parts, not family trees.',
    cards: [
      c('HOOK', 'The class explosion', 'You model notifications: `EmailNotifier`, `SmsNotifier`. Then someone wants email *and* SMS. Then SMS with retries. Then email with templating *and* retries.\n\nWith inheritance every new combination is a new subclass — and the number of combinations doubles with each feature.'),
      c('CONCEPT', 'Is-a versus has-a', '**Inheritance** says *is-a*: the subclass is fixed to its parent at write time and inherits everything, wanted or not.\n\n**Composition** says *has-a*: an object holds smaller collaborators and **delegates** to them. You can swap parts at runtime, test each part alone, and avoid the *fragile base class* problem, where a change in a parent silently breaks its children.'),
      c('EXAMPLE', 'One notifier, many channels', 'Instead of a subclass per combination, give `Notifier` a *list of channels*. Email and SMS each implement one tiny interface: `send`. “Email and SMS” is just a list with two items. Adding a Slack channel means one new class and zero changes to `Notifier`.'),
      c('CODE', 'Delegation', '', 'from typing import Protocol\n\nclass Channel(Protocol):\n    def send(self, to: str, msg: str) -> None: ...\n\nclass Email:\n    def send(self, to, msg): print(f"mail {to}: {msg}")\n\nclass Sms:\n    def send(self, to, msg): print(f"sms {to}: {msg}")\n\nclass Notifier:\n    def __init__(self, channels: list[Channel]):\n        self.channels = channels\n\n    def notify(self, to, msg):\n        for ch in self.channels:\n            ch.send(to, msg)\n\nNotifier([Email(), Sms()]).notify("a@b.c", "build is green")', 'python'),
      c('ANALOGY', 'LEGO versus a statue', 'Inheritance is carving a statue from a block: the shape is committed, and a new shape means a new block.\n\nComposition is LEGO: the same bricks, rearranged, build many things.'),
      c('WARNING', 'Not a ban on inheritance', 'Inherit when there is a genuine *is-a* and the subclass can stand in anywhere the parent is used (the Liskov substitution principle). A `Square` that extends `Rectangle` breaks the moment someone sets only the width.\n\nAnd don’t over-correct: one-method classes for everything, plus pages of forwarding code, is its own mess. Compose to vary behaviour; inherit to share a stable contract.'),
      c('CHECK', 'Choose', 'Q: You have `FileLogger` and `ConsoleLogger`, and now need “log to both, with timestamps.” Inherit or compose?\n\nA: Compose. A `Logger` that holds a list of sinks and an optional timestamp formatter gives you every combination from three small parts; the inheritance version needs `FileAndConsoleTimestampedLogger`.'),
      c('SUMMARY', 'In four lines', '- Inheritance = is-a, fixed at write time.\n- Composition = has-a, assembled and swapped at runtime.\n- Prefer composition when behaviour *varies*.\n- Inherit only for true substitutable is-a relationships.'),
    ],
  },
]
