import type { PackSeed } from './pack-util'
import { c } from './pack-util'

/** DSA toolkit + DBMS + networks — Weeks 2–4 topics. */
export const PACKS_DSA: PackSeed[] = [
  {
    key: 'py-dsa-toolkit',
    title: 'The Python DSA toolkit',
    topic: 'Python standard library for DSA',
    track: 'DSA',
    weekNumber: 2,
    tags: ['python', 'python dsa toolkit', 'arrays', 'hashing'],
    summary: 'list, dict, set, deque, heapq, bisect, Counter — and the hidden O(n) traps.',
    cards: [
      c('HOOK', 'Half of interview speed is your standard library', 'You know the algorithm; the next ten minutes go on writing a queue, a counter and a heap from scratch. Python ships all of them, tested and fast.\n\nKnow the six tools below cold, including what each one *costs*.'),
      c('CONCEPT', 'Six tools and their costs', '- **list**: dynamic array. `append`/`pop()` O(1) amortised; `pop(0)`, `insert(0, x)`, `x in lst` are **O(n)**.\n- **dict / set**: hash tables. Lookup/insert O(1) average.\n- **collections.deque**: O(1) at both ends. Your queue.\n- **heapq**: a *min*-heap on a plain list. Push/pop O(log n). For a max-heap, push negatives.\n- **bisect**: binary search on a sorted list, O(log n).\n- **Counter / defaultdict**: counting and grouping without the `if key in d` dance.'),
      c('EXAMPLE', 'Top-k frequent', 'Count with `Counter`, then pull the k largest with `heapq.nlargest`. Both lines are idiomatic, readable, and fast enough: O(n log k).\n\nBFS on a graph: adjacency list in a `defaultdict(list)`, frontier in a `deque`. No custom classes needed.'),
      c('CODE', 'The kit in action', '', 'from collections import Counter, defaultdict, deque\nimport heapq, bisect\n\nfreq = Counter("mississippi")\ntop2 = heapq.nlargest(2, freq, key=freq.get)\n\ngraph = defaultdict(list)\ngraph[1].append(2)\n\nq = deque([0])\nq.append(1)\nq.popleft()                 # O(1) — list.pop(0) would be O(n)\n\nh = []\nheapq.heappush(h, (3, "c"))\nheapq.heappop(h)            # smallest first\n\nnums = [1, 3, 5, 7]\nbisect.bisect_left(nums, 5) # 2', 'python'),
      c('ANALOGY', 'A knife roll', 'A chef doesn’t chop everything with one knife. Each blade is for a cut. Knowing which collection fits the access pattern — queue, counter, priority — is the same skill.'),
      c('WARNING', 'Traps that cost you the interview', '- `list.pop(0)` and `x in some_list` hide an O(n); inside a loop that’s O(n²).\n- `[[0] * n] * m` makes `m` references to **one** row. Use `[[0] * n for _ in range(m)]`.\n- `list.sort()` returns `None`; `sorted()` returns a new list.\n- Mutable default arguments (`def f(x, acc=[])`) persist between calls.\n- Default recursion limit is about 1000 frames; deep DFS may need an explicit stack.'),
      c('CHECK', 'Aliasing', 'Q: `grid = [[0] * 3] * 3; grid[0][0] = 1; print(grid)` — what prints?\n\nA: `[[1, 0, 0], [1, 0, 0], [1, 0, 0]]`. The outer `* 3` repeats a reference to the same inner list, so all three “rows” are one row.'),
      c('SUMMARY', 'In four lines', '- Queue = `deque`; counter = `Counter`; priority = `heapq`; search = `bisect`.\n- Know each operation’s cost; avoid `list.pop(0)` and `in list` in loops.\n- Build 2-D grids with a comprehension.\n- Max-heap = push negatives.'),
    ],
  },
  {
    key: 'dsa-two-pointers',
    title: 'Two pointers',
    topic: 'Two pointers technique',
    track: 'DSA',
    weekNumber: 2,
    tags: ['two pointers', 'arrays', 'strings'],
    summary: 'Two fingers and an invariant turn O(n²) pair-hunting into one pass.',
    cards: [
      c('HOOK', 'Brute force checks every pair', 'Find two numbers in a sorted array that sum to a target. Checking every pair is O(n²). Put one finger at each end and you finish in a single pass.\n\nThe skill isn’t the code — it’s knowing *why* a pointer can safely move.'),
      c('CONCEPT', 'Move one pointer, discard a whole family', 'Two indices walk a sequence under a rule that lets you rule out candidates safely.\n\n- **Opposite ends** (sorted arrays, palindromes, container with most water): start at both ends and move inward.\n- **Same direction** (slow/fast): remove duplicates in place, partition, find a cycle.\n\nIt works when there’s a **monotonic property**: moving a pointer provably can’t skip the answer.'),
      c('EXAMPLE', 'Two Sum on a sorted array', 'Compare `a[l] + a[r]` with the target.\n\n- Too small? `a[l]` is paired with the *largest* remaining value and still falls short, so `a[l]` can’t be part of any answer. Advance `l`.\n- Too big? `a[r]` is paired with the smallest remaining value and still overshoots, so retire `r`.\n\nEvery step eliminates one element for good.'),
      c('CODE', 'two_sum_sorted', '', 'def two_sum_sorted(a, target):\n    l, r = 0, len(a) - 1\n    while l < r:\n        s = a[l] + a[r]\n        if s == target:\n            return [l, r]\n        if s < target:\n            l += 1      # a[l] can\'t reach target even with the largest a[r]\n        else:\n            r -= 1      # a[r] overshoots even with the smallest a[l]\n    return []', 'python'),
      c('ANALOGY', 'Squeezing a rope', 'Hold a rope marked with numbers in both hands and slide your hands together. At every moment you know which end to move, because the rope is ordered. Without the order, you’d have no way to know.'),
      c('WARNING', 'Where it goes wrong', '- It needs sorted input (or another monotonic structure). On unsorted data, sort first or use a hash map.\n- `l < r` versus `l <= r`: for pairs you want strictly less.\n- 3Sum: skip equal neighbours or you’ll return duplicates.\n- The classic bug is moving the wrong pointer. Always state the invariant: *“everything outside [l, r] is already ruled out.”*'),
      c('CHECK', 'Container with most water', 'Q: heights `[1,8,6,2,5,4,8,3,7]`, `l = 0`, `r = 8`. Which pointer moves, and why?\n\nA: Move `l` (height 1 is the shorter wall). The area is capped by the shorter wall, so moving the taller one only reduces width without raising the cap. The best area found along the way is 49.'),
      c('SUMMARY', 'In four lines', '- Two indices + a monotonic rule = one pass.\n- Opposite ends for sorted/palindromic problems; slow/fast for in-place edits.\n- Always justify a move with an invariant.\n- Unsorted? Sort or hash first.'),
    ],
  },
  {
    key: 'dsa-sliding-window',
    title: 'Sliding window',
    topic: 'Sliding window technique',
    track: 'DSA',
    weekNumber: 3,
    tags: ['sliding window', 'arrays', 'strings', 'hashing'],
    summary: 'Expand, shrink, update incrementally — each element enters and leaves once.',
    cards: [
      c('HOOK', 'Don’t recompute the window', 'Longest substring without a repeated character. Recomputing every substring from scratch is O(n²) or worse.\n\nA window that **slides** — adding one element on the right, dropping one on the left — does it in O(n).'),
      c('CONCEPT', 'Expand right, shrink left', 'Keep a window `[l, r]` over the sequence plus a running state (a sum, a count map). Move `r` to take in the next element. When the constraint breaks, move `l` until it holds again.\n\nBecause each element is added once and removed at most once, the total work is O(n) — even though there’s a loop inside a loop.\n\nTwo flavours: **fixed size** (max sum of k elements) and **variable size** (longest/shortest window satisfying a condition).'),
      c('EXAMPLE', 'Longest substring without repeats', 'Remember the last index where each character was seen. When `ch` repeats *inside the current window*, jump `l` to just past its previous position. The window is always repeat-free, and the answer is the biggest window ever seen.'),
      c('CODE', 'longest_unique', '', 'def longest_unique(s):\n    last = {}              # char -> most recent index\n    best = l = 0\n    for r, ch in enumerate(s):\n        if ch in last and last[ch] >= l:\n            l = last[ch] + 1   # jump past the previous copy\n        last[ch] = r\n        best = max(best, r - l + 1)\n    return best\n\nlongest_unique("abcabcbb")     # 3', 'python'),
      c('ANALOGY', 'A caterpillar', 'The front reaches forward to the next leaf (expand). When it’s too long to fit the branch, the tail pulls up (shrink). It never goes back to re-measure its whole body — it just notes what changed at each end.'),
      c('WARNING', 'When the window lies', '- Shrinking must restore the constraint: use `while`, not `if`, when one step might need several removals.\n- The technique assumes that removing an element moves you *monotonically* toward valid. With negative numbers a running-sum window breaks; use prefix sums with a hash map instead.\n- Update state in the right order (add `a[r]` before checking, remove `a[l]` before moving `l`).\n- Check `k > n`, empty input and all-identical input.'),
      c('CHECK', 'The O(1) update', 'Q: For the maximum sum of any `k` consecutive elements, what changes when the window moves one step?\n\nA: `sum += a[r] - a[r - k]`: add the new element, subtract the one that left. That’s O(1) per step and O(n) overall, instead of re-adding `k` numbers every time.'),
      c('SUMMARY', 'In four lines', '- Window `[l, r]` + running state.\n- Grow `r`; shrink `l` while the constraint is broken.\n- Each element enters once and leaves once → O(n).\n- Needs a monotonic constraint; negatives call for prefix sums.'),
    ],
  },
  {
    key: 'dsa-binary-search',
    title: 'Binary search boundaries',
    topic: 'Binary search and boundaries',
    track: 'DSA',
    weekNumber: 4,
    tags: ['binary search', 'arrays'],
    summary: 'Stop guessing `<=` vs `<`: search for the first index where a predicate turns true.',
    cards: [
      c('HOOK', 'Five lines, endless bugs', 'Binary search is five lines long, and most people still get it wrong the first few times. The culprit is always one character: `<` or `<=`, `mid` or `mid + 1`.\n\nThere is one framing that removes the guesswork.'),
      c('CONCEPT', 'First index where the predicate is true', 'Instead of “find x”, ask: over indices `0…n`, find the **first** `i` where `pred(i)` is true, given that `pred` looks like `false…false true…true`.\n\nKeep the answer in a half-open range `[lo, hi)`. Compute `mid = lo + (hi - lo) // 2`. If `pred(mid)`, the answer is at `mid` or earlier: `hi = mid`. Otherwise it’s later: `lo = mid + 1`. Stop when `lo == hi`.\n\n**Lower bound** is “first `a[i] >= x`”. **Upper bound** is “first `a[i] > x`”. The same template also solves “search on the answer” (minimum speed, smallest capacity).'),
      c('EXAMPLE', 'First, last and count', 'The first occurrence of `x` is `lower_bound(x)`. One past the last is `lower_bound(x + 1)` for integers. So the count of `x` is the difference between the two — two O(log n) searches, no special cases for duplicates.'),
      c('CODE', 'lower_bound', '', 'def lower_bound(a, x):            # first i with a[i] >= x (len(a) if none)\n    lo, hi = 0, len(a)\n    while lo < hi:\n        mid = lo + (hi - lo) // 2\n        if a[mid] >= x:\n            hi = mid\n        else:\n            lo = mid + 1\n    return lo\n\ndef count_of(a, x):               # integers only\n    return lower_bound(a, x + 1) - lower_bound(a, x)', 'python'),
      c('ANALOGY', 'The dictionary flip', 'Looking for the first word starting with “st”, you open near the middle: if the page is already past “st”, the answer is here or earlier; if it’s before, it’s later. You never ask “is this exactly it?” — only “which side of the line am I on?”'),
      c('WARNING', 'The usual suspects', '- `(lo + hi) // 2` can overflow in fixed-width integer languages (C++/Java). Use `lo + (hi - lo) / 2`.\n- Mixing a closed range `[lo, hi]` with `hi = mid` loops forever when `mid == lo`.\n- The predicate **must** be monotonic. If it isn’t, there is no boundary to find.\n- Decide, before coding, what to return when nothing satisfies the predicate (`len(a)` here).'),
      c('CHECK', 'Read the output', 'Q: `a = [1, 2, 2, 2, 3]`. What do `lower_bound(a, 2)` and `lower_bound(a, 3)` return, and what does that tell you?\n\nA: `1` and `4`. The difference is 3, so the value 2 occurs three times.'),
      c('SUMMARY', 'In four lines', '- Frame it as “first index where `pred` is true”.\n- Half-open `[lo, hi)`, `hi = mid` on true, `lo = mid + 1` on false.\n- Lower/upper bound give first/last/count.\n- The predicate must be monotonic.'),
    ],
  },
  {
    key: 'db-acid-isolation',
    title: 'ACID & isolation levels',
    topic: 'Transactions: ACID and isolation',
    track: 'CORE_CS',
    weekNumber: 4,
    tags: ['dbms', 'transactions', 'acid', 'sql'],
    summary: 'What “transaction” really guarantees, and which anomalies each isolation level allows.',
    cards: [
      c('HOOK', 'Where did the ₹500 go?', 'You transfer ₹500 from account A to account B. The debit succeeds; the server crashes before the credit. Without transactions the money has simply vanished.\n\nA **transaction** is the database’s promise that this can’t happen.'),
      c('CONCEPT', 'ACID', '- **Atomicity**: all of it or none of it (undo log / rollback).\n- **Consistency**: a transaction takes the database from one valid state to another; constraints hold.\n- **Isolation**: concurrent transactions don’t see each other’s half-finished work.\n- **Durability**: once committed, it survives a crash (write-ahead log flushed to disk).\n\nIsolation comes in levels, trading safety for throughput. The SQL standard names three anomalies: **dirty read** (see uncommitted data), **non-repeatable read** (a row changes between two reads), **phantom read** (new rows appear in a repeated query).'),
      c('EXAMPLE', 'A non-repeatable read', 'T1 reads Alice’s balance: 100. T2 withdraws 50 and commits. T1 reads the balance again: 50. Same transaction, same query, different answer.\n\n`READ COMMITTED` allows this. `REPEATABLE READ` prevents it by giving T1 a stable view of rows it has read.'),
      c('CODE', 'A transfer', 'Both statements take effect, or neither does:', 'BEGIN;\nUPDATE accounts SET balance = balance - 500 WHERE id = 1;\nUPDATE accounts SET balance = balance + 500 WHERE id = 2;\nCOMMIT;   -- on error or ROLLBACK, neither update happens\n\n-- PostgreSQL syntax; choose the level before the first statement\nBEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;', 'sql'),
      c('ANALOGY', 'Frosted-glass cubicles', 'Atomicity is posting a whole slip to the ledger or tearing it up. Isolation is giving every clerk a frosted-glass cubicle: they can work at the same time, but nobody sees another’s scribbles until the slip is filed.'),
      c('WARNING', 'Defaults differ, names mislead', 'PostgreSQL defaults to `READ COMMITTED`; MySQL’s InnoDB defaults to `REPEATABLE READ`. In PostgreSQL, `REPEATABLE READ` is snapshot isolation: it blocks phantoms but still permits *write skew*, so only `SERIALIZABLE` prevents every anomaly. Stronger isolation costs throughput, and `SERIALIZABLE` may abort transactions that you must retry.\n\nAlso, “consistency” in ACID is not the “consistency” in the CAP theorem.'),
      c('CHECK', 'Name the anomaly', 'Q: T1 runs `SELECT COUNT(*) FROM emp WHERE dept = \'ENG\'` twice. Between the runs, T2 inserts an ENG employee and commits. The counts differ. What anomaly is this, and which standard level first prevents it?\n\nA: A **phantom read**. By the SQL standard, only `SERIALIZABLE` prevents it (PostgreSQL’s snapshot-based `REPEATABLE READ` also does).'),
      c('SUMMARY', 'In four lines', '- Atomic, Consistent, Isolated, Durable.\n- Dirty < non-repeatable < phantom: each level blocks more anomalies.\n- Know your database’s default level.\n- Higher isolation = fewer anomalies, lower throughput, more retries.'),
    ],
  },
  {
    key: 'db-b-plus-trees',
    title: 'B+ trees',
    topic: 'B+ tree indexes',
    track: 'CORE_CS',
    weekNumber: 4,
    tags: ['dbms', 'indexes', 'b+ trees', 'storage'],
    summary: 'Why a million-row lookup touches three or four disk pages — and why indexes aren’t free.',
    cards: [
      c('HOOK', 'Three page reads for a million rows', 'A table has a million rows. A lookup by primary key touches about three or four disk pages, not twenty. The reason is that disks are read in **pages**, and a B+ tree is built so that each page narrows the search by hundreds.'),
      c('CONCEPT', 'Wide, shallow, sorted at the bottom', 'A **B+ tree** is a balanced, multiway search tree:\n\n- **Internal nodes** hold only keys and child pointers, so many fit per page: a *fanout* of hundreds.\n- **Leaves** hold the keys with their row pointers (or the rows themselves) and are chained in a **sorted linked list**.\n- Every leaf is at the same depth, so height ≈ log\\_fanout(n): about 3–4 for millions of rows.\n\nOne node ≈ one disk page, so one level ≈ one I/O.'),
      c('EXAMPLE', 'Range queries are cheap', '`WHERE id BETWEEN 100 AND 200`: descend once to the leaf holding 100, then walk the leaf chain right until you pass 200. No re-descending.\n\nThat’s the edge over a hash index (no range scans) and over a plain B-tree (which stores data in internal nodes, lowering fanout and breaking the leaf chain).\n\n**Insert**: find the leaf; if it’s full, split it and push the middle key up. Splits can cascade to the root, which is the only way the tree grows taller.'),
      c('CODE', 'Point lookup', '', 'import bisect\n\ndef search(node, key):\n    while not node.is_leaf:\n        i = bisect.bisect_right(node.keys, key)   # which child covers key\n        node = node.children[i]\n    i = bisect.bisect_left(node.keys, key)\n    if i < len(node.keys) and node.keys[i] == key:\n        return node.values[i]\n    return None', 'python'),
      c('ANALOGY', 'Library signage', 'Floor → aisle → shelf → book. Each sign narrows the choice a hundredfold, so you reach the right shelf in three glances. And the books on the shelf are in order, so the next one is right beside the last.'),
      c('WARNING', 'Indexes cost something', '- Every index must be updated on every write: more indexes, slower inserts.\n- Random keys (such as UUIDv4) scatter inserts across leaves and cause page splits; sequential keys append at the right edge.\n- A composite index on `(a, b)` helps queries on `a` or on `a, b` — not on `b` alone (leftmost-prefix rule).\n- `LIKE \'%abc\'` can’t use the sort order. Neither does a function wrapped around the column.'),
      c('CHECK', 'Estimate the height', 'Q: Fanout ≈ 200 and 1 million keys. About how many levels deep?\n\nA: About 3. 200² = 40,000 and 200³ = 8,000,000 ≥ 1,000,000, so root + one internal level + leaves, roughly 3–4 page reads, with the root usually cached.'),
      c('SUMMARY', 'In four lines', '- Internal nodes route; leaves store; leaves are linked.\n- Height ≈ log(fanout) → a handful of I/Os for millions of rows.\n- Linked leaves make range scans fast.\n- Each index speeds reads and slows writes.'),
    ],
  },
  {
    key: 'net-http-request',
    title: 'What happens in an HTTP request',
    topic: 'From URL to page: DNS, TCP, TLS, HTTP',
    track: 'CORE_CS',
    weekNumber: 4,
    tags: ['networks', 'http', 'dns', 'tls'],
    summary: 'Type a URL, press Enter: DNS, TCP, TLS, then the request — and why round trips are the cost.',
    cards: [
      c('HOOK', 'About 100 ms, a lot of steps', 'You type a URL and press Enter. A moment later, a page appears. In between, your machine looked up a name, opened a connection, agreed on encryption, asked for a document and parsed the answer.\n\nBeing able to narrate this sequence is a classic interview question and a genuine debugging tool.'),
      c('CONCEPT', 'The sequence', '1. **Parse & check**: URL parts; browser cache; HSTS (“always HTTPS for this host”).\n2. **DNS**: name → IP. Browser/OS cache → recursive resolver → root → TLD → authoritative server.\n3. **TCP handshake**: SYN, SYN-ACK, ACK (HTTP/3 uses QUIC over UDP instead).\n4. **TLS handshake**: verify the server’s certificate, derive session keys (TLS 1.3 needs one round trip).\n5. **HTTP request**: method, path, headers.\n6. **Response**: status, headers, body — often via a CDN or load balancer.\n7. **Render**: parse HTML, fetch subresources, ideally reusing the connection.'),
      c('EXAMPLE', 'What the wire looks like', 'HTTP/1.1 is plain text. The request is a line plus headers; the response is a status line, headers, a blank line, then the body. `Host` lets one IP serve many sites; `Cache-Control` tells the browser how long it may reuse the answer without asking again.'),
      c('CODE', 'A request and its response', '', 'GET /index.html HTTP/1.1\nHost: example.com\nAccept: text/html\n\nHTTP/1.1 200 OK\nContent-Type: text/html; charset=utf-8\nCache-Control: max-age=3600\n\n<!doctype html>…', 'http'),
      c('ANALOGY', 'Posting a letter', 'DNS is looking up the address in a directory. TCP is phoning to check someone’s home. TLS is agreeing a secret code. Only then do you send the letter (HTTP) and wait for the reply.'),
      c('WARNING', 'Latency is round trips', 'Each step above can cost a full round trip, and round trips are bounded by the speed of light, not by your bandwidth. That’s why connection reuse (keep-alive, HTTP/2 multiplexing), CDNs and `preconnect` matter.\n\nAlso remember: HTTP is **stateless** (cookies and tokens add state); status classes are 2xx success, 3xx redirect, 4xx client error, 5xx server error; and HTTPS means the channel is private, not that the site is trustworthy. DNS caches obey TTLs, so changes propagate slowly.'),
      c('CHECK', 'Why a CDN helps dynamic pages too', 'Q: Why can a CDN speed up the first byte of even an uncacheable, dynamic page?\n\nA: The TCP and TLS handshakes finish with a nearby edge server (short round trips), and the edge keeps a warm, reused connection to the origin, so the expensive long-distance hops are paid once instead of per user.'),
      c('SUMMARY', 'In four lines', '- DNS → TCP → TLS → HTTP request → response → render.\n- Round trips, not bandwidth, dominate latency.\n- Reuse connections; get closer to the user.\n- HTTP is stateless; HTTPS is private, not “safe”.'),
    ],
  },
]
